version: '3'

networks:
  lab_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  # Серверы хранения
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Web Console
    networks:
      lab_net:
        ipv4_address: 172.20.0.101

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      lab_net:
        ipv4_address: 172.20.0.102

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      lab_net:
        ipv4_address: 172.20.0.103

  # Серверы с генерацией логов
  web1:
    build: 
      context: ./web_server
      args:
        SERVER_TYPE: web
    container_name: web1
    environment:
      - SERVER_TYPE=web
    networks:
      lab_net:
        ipv4_address: 172.20.0.11
  web2:
    build: 
      context: ./web_server
      args:
        SERVER_TYPE: web
    container_name: web2
    networks:
      lab_net:
        ipv4_address: 172.20.0.12

  app1:
    build: 
      context: ./app_server
      args:
        SERVER_TYPE: app
    container_name: app1
    environment:
      - SERVER_TYPE=app
    networks:
      lab_net:
        ipv4_address: 172.20.0.21
  app2:
    build: 
      context: ./app_server
      args:
        SERVER_TYPE: app
    container_name: app2
    networks:
      lab_net:
        ipv4_address: 172.20.0.22

  int1:
    build: 
      context: ./integration_server
      args:
        SERVER_TYPE: integration
    container_name: int1
    environment:
      - SERVER_TYPE=integration
    networks:
      lab_net:
        ipv4_address: 172.20.0.31
  int2:
    build: 
      context: ./integration_server
      args:
        SERVER_TYPE: integration
    container_name: int2
    networks:
      lab_net:
        ipv4_address: 172.20.0.32

volumes:
  minio_data:
  es_data: