FROM python:3.9-alpine

ARG SERVER_TYPE
ENV SERVER_TYPE=${SERVER_TYPE}

WORKDIR /app

# Установка зависимостей (Alpine использует `apk`)
RUN apk add --no-cache \
    procps \
    curl \
    && mkdir -p /var/log/${SERVER_TYPE} \
    && chmod -R 777 /var/log

# Копируем Filebeat из локальной папки
COPY ../filebeat-8.13.4-linux-x86_64.tar.gz /tmp/
# Установка Filebeat
RUN tar xzvf /tmp/filebeat-8.13.4-linux-x86_64.tar.gz -C /usr/share/ \
    && rm /tmp/filebeat-8.13.4-linux-x86_64.tar.gz \
    && mv /usr/share/filebeat-8.13.4-linux-x86_64 /usr/share/filebeat \
    && mkdir -p /var/log/${SERVER_TYPE}/blog

# Копирование конфигов
COPY log_generator.py /app/log_generator.py
COPY filebeat.yml /usr/share/filebeat/filebeat.yml

# Права
RUN chmod go-w /usr/share/filebeat/filebeat.yml \
    && chown root:root /usr/share/filebeat/filebeat.yml

CMD (cd /usr/share/filebeat && ./filebeat -e -c filebeat.yml) & python /app/log_generator.py