version: '3'

networks:
  lab_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  web1:
    build: 
      context: ./web_server
      args:
        SERVER_TYPE: web
    container_name: web1
    environment:
      - SERVER_TYPE=web
    networks:
      lab_net:
        ipv4_address: 172.20.0.11
  web2:
    build: 
      context: ./web_server
      args:
        SERVER_TYPE: web
    container_name: web2
    networks:
      lab_net:
        ipv4_address: 172.20.0.12

  app1:
    build: 
      context: ./app_server
      args:
        SERVER_TYPE: app
    container_name: app1
    environment:
      - SERVER_TYPE=app
    networks:
      lab_net:
        ipv4_address: 172.20.0.21
  app2:
    build: 
      context: ./app_server
      args:
        SERVER_TYPE: app
    container_name: app2
    networks:
      lab_net:
        ipv4_address: 172.20.0.22

  int1:
    build: 
      context: ./integration_server
      args:
        SERVER_TYPE: integration
    container_name: int1
    environment:
      - SERVER_TYPE=integration
    networks:
      lab_net:
        ipv4_address: 172.20.0.31
  int2:
    build: 
      context: ./integration_server
      args:
        SERVER_TYPE: integration
    container_name: int2
    networks:
      lab_net:
        ipv4_address: 172.20.0.32