FROM python:3.9-alpine

ARG SERVER_TYPE
ENV SERVER_TYPE=${SERVER_TYPE}

WORKDIR /app

# 1. Создание директорий для логов
RUN mkdir -p /var/log/${SERVER_TYPE}/blog \
    && chmod -R 777 /var/log

# 2. Установка зависимостей для сборки
RUN apk add --no-cache \
    procps \
    curl \
    go \
    git \
    make \
    gcc \
    musl-dev

# 3. Сборка Filebeat
RUN git clone --branch v8.13.4 --depth 1 https://github.com/elastic/beats.git \
    && cd beats/filebeat \
    && GOOS=linux GOARCH=amd64 make \
    && mkdir -p /usr/share/filebeat \
    && mv filebeat /usr/share/filebeat/ \
    && chmod +x /usr/share/filebeat/filebeat \
    && rm -rf /beats

# 4. Копирование конфигов
COPY log_generator.py /app/log_generator.py
COPY filebeat.yml /usr/share/filebeat/filebeat.yml

# 5. Установка прав (исправлено)
RUN chmod go-w /usr/share/filebeat/filebeat.yml \
    && chown root:root /usr/share/filebeat/filebeat.yml

# 6. Запуск
CMD ["sh", "-c", "/usr/share/filebeat/filebeat -c /usr/share/filebeat/filebeat.yml --quiet & python /app/log_generator.py"]