# minio_config.yml
minio:
  buckets:
    - name: "logs-raw"
      structure:
        - "APP/simple"
        - "APP/blog"
        - "WEB/simple"
        - "WEB/blog"
        - "INT/simple"
        - "INT/blog"

elasticsearch:
  indices:
    - "logs-app-simple"
    - "logs-app-blog" 
    - "logs-web-simple"
    - "logs-web-blog"
    - "logs-int-simple"
    - "logs-int-blog"